'use strict';

module.exports = {
  breakfast: {
    veg: [
      { name: 'Aloo Paratha with Curd', calories: 320, proteinG: 10, carbsG: 45, fatG: 12, estimated: true },
      { name: 'Poha with Peanuts', calories: 280, proteinG: 9, carbsG: 38, fatG: 9, estimated: true },
      { name: 'Upma with Chutney', calories: 250, proteinG: 8, carbsG: 40, fatG: 6, estimated: true },
      { name: 'Besan Chilla', calories: 220, proteinG: 10, carbsG: 28, fatG: 8, estimated: true },
      { name: 'Puri with Aloo Bhaji', calories: 380, proteinG: 9, carbsG: 50, fatG: 16, estimated: true },
      { name: 'Methi Paratha', calories: 300, proteinG: 11, carbsG: 42, fatG: 11, estimated: true },
      { name: 'Dal Paratha', calories: 310, proteinG: 13, carbsG: 44, fatG: 10, estimated: true },
      { name: 'Sooji Halwa with Puri', calories: 350, proteinG: 8, carbsG: 48, fatG: 14, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Paratha', calories: 340, proteinG: 14, carbsG: 42, fatG: 14, estimated: true },
      { name: 'Egg Bhurji with Roti', calories: 310, proteinG: 15, carbsG: 35, fatG: 12, estimated: true },
      { name: 'Masala Omelette with Poha', calories: 300, proteinG: 14, carbsG: 38, fatG: 11, estimated: true },
      { name: 'Egg Frankie', calories: 330, proteinG: 15, carbsG: 40, fatG: 13, estimated: true },
      { name: 'Egg Kathi Roll', calories: 350, proteinG: 16, carbsG: 42, fatG: 14, estimated: true },
    ],
    'non-veg': [
      { name: 'Keema Paratha', calories: 380, proteinG: 18, carbsG: 42, fatG: 16, estimated: true },
      { name: 'Chicken Frankie', calories: 360, proteinG: 20, carbsG: 38, fatG: 14, estimated: true },
      { name: 'Mutton Kheema with Puri', calories: 420, proteinG: 22, carbsG: 45, fatG: 18, estimated: true },
      { name: 'Chicken Tikka Breakfast Bowl', calories: 340, proteinG: 28, carbsG: 30, fatG: 12, estimated: true },
      { name: 'Prawn Masala with Roti', calories: 320, proteinG: 24, carbsG: 32, fatG: 10, estimated: true },
    ],
  },
  lunch: {
    veg: [
      { name: 'Dal Tadka with Roti', calories: 280, proteinG: 12, carbsG: 42, fatG: 6, estimated: true },
      { name: 'Paneer Butter Masala with Rice', calories: 420, proteinG: 18, carbsG: 48, fatG: 16, estimated: true },
      { name: 'Rajma Chawal', calories: 350, proteinG: 14, carbsG: 52, fatG: 6, estimated: true },
      { name: 'Chole Bhature', calories: 480, proteinG: 16, carbsG: 62, fatG: 18, estimated: true },
      { name: 'Sabzi with Roti', calories: 260, proteinG: 9, carbsG: 38, fatG: 8, estimated: true },
      { name: 'Palak Paneer with Rice', calories: 380, proteinG: 16, carbsG: 45, fatG: 14, estimated: true },
      { name: 'Kadhi Chawal', calories: 320, proteinG: 11, carbsG: 48, fatG: 8, estimated: true },
      { name: 'Aloo Gobi with Roti', calories: 280, proteinG: 8, carbsG: 40, fatG: 10, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Curry with Roti', calories: 340, proteinG: 16, carbsG: 40, fatG: 12, estimated: true },
      { name: 'Egg Biryani', calories: 450, proteinG: 18, carbsG: 55, fatG: 16, estimated: true },
      { name: 'Egg Masala with Rice', calories: 400, proteinG: 17, carbsG: 50, fatG: 14, estimated: true },
      { name: 'Egg Bhurji with Paratha', calories: 380, proteinG: 15, carbsG: 42, fatG: 15, estimated: true },
      { name: 'Egg Fried Rice', calories: 420, proteinG: 14, carbsG: 52, fatG: 16, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Biryani', calories: 480, proteinG: 28, carbsG: 52, fatG: 16, estimated: true },
      { name: 'Mutton Rogan Josh with Rice', calories: 520, proteinG: 32, carbsG: 48, fatG: 20, estimated: true },
      { name: 'Butter Chicken with Naan', calories: 500, proteinG: 28, carbsG: 45, fatG: 22, estimated: true },
      { name: 'Fish Curry with Rice', calories: 420, proteinG: 26, carbsG: 50, fatG: 12, estimated: true },
      { name: 'Lamb Curry with Roti', calories: 480, proteinG: 30, carbsG: 42, fatG: 18, estimated: true },
      { name: 'Chicken Korma with Rice', calories: 460, proteinG: 26, carbsG: 50, fatG: 16, estimated: true },
      { name: 'Prawn Masala with Rice', calories: 420, proteinG: 28, carbsG: 48, fatG: 12, estimated: true },
      { name: 'Mutton Biryani', calories: 520, proteinG: 32, carbsG: 50, fatG: 20, estimated: true },
    ],
  },
  snack: {
    veg: [
      { name: 'Samosa with Chutney', calories: 220, proteinG: 6, carbsG: 28, fatG: 10, estimated: true },
      { name: 'Pakoda with Chai', calories: 200, proteinG: 5, carbsG: 26, fatG: 9, estimated: true },
      { name: 'Bhel Puri', calories: 180, proteinG: 6, carbsG: 28, fatG: 6, estimated: true },
      { name: 'Dahi Puri', calories: 160, proteinG: 6, carbsG: 22, fatG: 5, estimated: true },
      { name: 'Lassi', calories: 150, proteinG: 5, carbsG: 20, fatG: 4, estimated: true },
      { name: 'Roasted Chana', calories: 140, proteinG: 9, carbsG: 18, fatG: 4, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Puff', calories: 200, proteinG: 8, carbsG: 22, fatG: 9, estimated: true },
      { name: 'Egg Roll', calories: 210, proteinG: 9, carbsG: 24, fatG: 9, estimated: true },
      { name: 'Boiled Eggs with Chaat Masala', calories: 180, proteinG: 13, carbsG: 12, fatG: 8, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Tikka', calories: 200, proteinG: 18, carbsG: 8, fatG: 10, estimated: true },
      { name: 'Seekh Kebab', calories: 210, proteinG: 20, carbsG: 6, fatG: 11, estimated: true },
      { name: 'Mutton Shammi Kebab', calories: 220, proteinG: 22, carbsG: 8, fatG: 11, estimated: true },
    ],
  },
  dinner: {
    veg: [
      { name: 'Paneer Tikka Masala with Naan', calories: 480, proteinG: 20, carbsG: 50, fatG: 18, estimated: true },
      { name: 'Dal Makhani with Rice', calories: 420, proteinG: 14, carbsG: 52, fatG: 14, estimated: true },
      { name: 'Mixed Veg Sabzi with Roti', calories: 280, proteinG: 9, carbsG: 40, fatG: 9, estimated: true },
      { name: 'Palak Khichdi', calories: 320, proteinG: 11, carbsG: 45, fatG: 9, estimated: true },
      { name: 'Baingan Bharta with Roti', calories: 290, proteinG: 8, carbsG: 38, fatG: 11, estimated: true },
      { name: 'Rajma Rice', calories: 360, proteinG: 14, carbsG: 52, fatG: 7, estimated: true },
      { name: 'Methi Dal Roti', calories: 300, proteinG: 13, carbsG: 44, fatG: 7, estimated: true },
      { name: 'Aloo Matar with Paratha', calories: 380, proteinG: 10, carbsG: 50, fatG: 14, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Curry with Rice', calories: 380, proteinG: 17, carbsG: 48, fatG: 12, estimated: true },
      { name: 'Egg Paratha with Curd', calories: 380, proteinG: 15, carbsG: 44, fatG: 14, estimated: true },
      { name: 'Egg Masala with Roti', calories: 340, proteinG: 16, carbsG: 40, fatG: 12, estimated: true },
      { name: 'Egg Biryani', calories: 460, proteinG: 18, carbsG: 56, fatG: 16, estimated: true },
      { name: 'Anda Bhurji with Naan', calories: 400, proteinG: 17, carbsG: 46, fatG: 14, estimated: true },
    ],
    'non-veg': [
      { name: 'Butter Chicken with Roti', calories: 480, proteinG: 28, carbsG: 42, fatG: 20, estimated: true },
      { name: 'Mutton Biryani', calories: 540, proteinG: 32, carbsG: 52, fatG: 20, estimated: true },
      { name: 'Fish Curry with Rice', calories: 420, proteinG: 26, carbsG: 50, fatG: 12, estimated: true },
      { name: 'Chicken Tikka Masala with Naan', calories: 500, proteinG: 30, carbsG: 46, fatG: 18, estimated: true },
      { name: 'Prawn Curry with Rice', calories: 420, proteinG: 28, carbsG: 48, fatG: 11, estimated: true },
      { name: 'Lamb Seekh Kebab with Paratha', calories: 480, proteinG: 28, carbsG: 44, fatG: 18, estimated: true },
      { name: 'Chicken Biryani', calories: 500, proteinG: 28, carbsG: 54, fatG: 16, estimated: true },
      { name: 'Mutton Shorba Rice', calories: 480, proteinG: 30, carbsG: 48, fatG: 16, estimated: true },
    ],
  },
};
