'use strict';

module.exports = {
  breakfast: {
    veg: [
      { name: 'Idli with Sambar', calories: 96, proteinG: 2.8, carbsG: 19.0, fatG: 0.3, estimated: true },
      { name: 'Masala Dosa', calories: 215, proteinG: 6.5, carbsG: 35.0, fatG: 5.2, estimated: true },
      { name: 'Rava Upma', calories: 152, proteinG: 4.0, carbsG: 25.0, fatG: 3.5, estimated: true },
      { name: 'Pongal with Chutney', calories: 180, proteinG: 5.2, carbsG: 32.0, fatG: 3.0, estimated: true },
      { name: 'Medu Vada', calories: 155, proteinG: 6.0, carbsG: 16.0, fatG: 6.5, estimated: true },
      { name: 'Rava Idli', calories: 85, proteinG: 2.2, carbsG: 16.0, fatG: 0.5, estimated: true },
      { name: 'Oats Pongal', calories: 140, proteinG: 4.5, carbsG: 24.0, fatG: 2.0, estimated: true },
      { name: 'Pesarattu with Ginger Chutney', calories: 165, proteinG: 7.0, carbsG: 26.0, fatG: 2.5, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Dosa', calories: 245, proteinG: 9.0, carbsG: 32.0, fatG: 8.0, estimated: true },
      { name: 'Egg Upma', calories: 195, proteinG: 8.5, carbsG: 22.0, fatG: 6.5, estimated: true },
      { name: 'Egg Parotta', calories: 285, proteinG: 10.0, carbsG: 30.0, fatG: 12.0, estimated: true },
      { name: 'Masala Egg Omelette with Idli', calories: 210, proteinG: 9.5, carbsG: 24.0, fatG: 7.0, estimated: true },
      { name: 'Scrambled Eggs with Appam', calories: 225, proteinG: 8.0, carbsG: 28.0, fatG: 7.5, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Keema Dosa', calories: 265, proteinG: 12.0, carbsG: 33.0, fatG: 9.0, estimated: true },
      { name: 'Fish Curry with Idli', calories: 195, proteinG: 14.0, carbsG: 20.0, fatG: 5.0, estimated: true },
      { name: 'Prawn Masala with Appam', calories: 210, proteinG: 13.5, carbsG: 26.0, fatG: 4.5, estimated: true },
      { name: 'Mutton Kheema with Parotta', calories: 320, proteinG: 15.0, carbsG: 32.0, fatG: 13.0, estimated: true },
      { name: 'Chicken Chettinad Breakfast Bowl', calories: 280, proteinG: 18.0, carbsG: 28.0, fatG: 9.5, estimated: true },
    ],
  },
  lunch: {
    veg: [
      { name: 'Sambar Rice with Papad', calories: 285, proteinG: 7.0, carbsG: 52.0, fatG: 4.0, estimated: true },
      { name: 'Vegetable Biryani', calories: 310, proteinG: 8.0, carbsG: 48.0, fatG: 8.5, estimated: true },
      { name: 'Rasam Rice with Poriyal', calories: 245, proteinG: 6.5, carbsG: 48.0, fatG: 2.0, estimated: true },
      { name: 'Curd Rice with Pickle', calories: 220, proteinG: 5.5, carbsG: 40.0, fatG: 3.5, estimated: true },
      { name: 'Kootu Curry with Rice', calories: 270, proteinG: 7.0, carbsG: 48.0, fatG: 4.5, estimated: true },
      { name: 'Tamarind Rice', calories: 255, proteinG: 5.0, carbsG: 50.0, fatG: 2.5, estimated: true },
      { name: 'Vegetable Kuzhambu with Rice', calories: 265, proteinG: 6.0, carbsG: 50.0, fatG: 3.0, estimated: true },
      { name: 'Tomato Rice with Raita', calories: 240, proteinG: 5.5, carbsG: 46.0, fatG: 2.5, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Curry with Rice', calories: 320, proteinG: 11.0, carbsG: 50.0, fatG: 7.0, estimated: true },
      { name: 'Egg Biryani', calories: 360, proteinG: 12.0, carbsG: 50.0, fatG: 11.0, estimated: true },
      { name: 'Egg Masala with Parotta', calories: 340, proteinG: 10.0, carbsG: 42.0, fatG: 12.0, estimated: true },
      { name: 'Egg Kuzhambu with Rice', calories: 315, proteinG: 10.0, carbsG: 50.0, fatG: 7.5, estimated: true },
      { name: 'Egg Fried Rice', calories: 305, proteinG: 10.5, carbsG: 48.0, fatG: 6.5, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Chettinad with Rice', calories: 380, proteinG: 20.0, carbsG: 48.0, fatG: 12.0, estimated: true },
      { name: 'Fish Curry with Rice', calories: 340, proteinG: 18.0, carbsG: 48.0, fatG: 8.0, estimated: true },
      { name: 'Prawn Biryani', calories: 360, proteinG: 16.0, carbsG: 50.0, fatG: 10.0, estimated: true },
      { name: 'Mutton Kuzhambu with Rice', calories: 395, proteinG: 19.0, carbsG: 48.0, fatG: 14.0, estimated: true },
      { name: 'Chicken Biryani', calories: 385, proteinG: 19.0, carbsG: 50.0, fatG: 12.5, estimated: true },
      { name: 'Fish Fry with Sambar Rice', calories: 355, proteinG: 17.5, carbsG: 50.0, fatG: 9.5, estimated: true },
      { name: 'Prawn Masala with Rice', calories: 345, proteinG: 16.0, carbsG: 48.0, fatG: 9.0, estimated: true },
      { name: 'Chicken 65 Rice Bowl', calories: 370, proteinG: 18.0, carbsG: 48.0, fatG: 11.0, estimated: true },
    ],
  },
  snack: {
    veg: [
      { name: 'Murukku with Tea', calories: 135, proteinG: 2.0, carbsG: 18.0, fatG: 5.5, estimated: true },
      { name: 'Sundal', calories: 95, proteinG: 4.5, carbsG: 12.0, fatG: 2.5, estimated: true },
      { name: 'Banana Chips', calories: 165, proteinG: 1.0, carbsG: 20.0, fatG: 8.5, estimated: true },
      { name: 'Onion Pakoda', calories: 145, proteinG: 3.0, carbsG: 16.0, fatG: 6.5, estimated: true },
      { name: 'Tapioca Chips', calories: 155, proteinG: 0.5, carbsG: 20.0, fatG: 7.5, estimated: true },
      { name: 'Coconut Ladoo', calories: 120, proteinG: 2.5, carbsG: 14.0, fatG: 5.5, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Bhurji on Toast', calories: 185, proteinG: 8.0, carbsG: 18.0, fatG: 7.0, estimated: true },
      { name: 'Boiled Egg with Pepper', calories: 95, proteinG: 6.5, carbsG: 1.0, fatG: 7.0, estimated: true },
      { name: 'Egg Puff', calories: 210, proteinG: 6.0, carbsG: 22.0, fatG: 10.0, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Lollipop', calories: 195, proteinG: 12.0, carbsG: 12.0, fatG: 9.0, estimated: true },
      { name: 'Fish Fry Bites', calories: 175, proteinG: 14.0, carbsG: 8.0, fatG: 7.5, estimated: true },
      { name: 'Prawn Fry', calories: 165, proteinG: 13.5, carbsG: 6.0, fatG: 7.0, estimated: true },
    ],
  },
  dinner: {
    veg: [
      { name: 'Chapati with Vegetable Curry', calories: 240, proteinG: 6.0, carbsG: 42.0, fatG: 4.0, estimated: true },
      { name: 'Dosa with Sambar', calories: 235, proteinG: 7.0, carbsG: 40.0, fatG: 5.0, estimated: true },
      { name: 'Parotta with Salna', calories: 275, proteinG: 6.0, carbsG: 42.0, fatG: 7.5, estimated: true },
      { name: 'Idiyappam with Coconut Milk', calories: 215, proteinG: 4.5, carbsG: 40.0, fatG: 3.5, estimated: true },
      { name: 'Pongal with Vada', calories: 245, proteinG: 7.5, carbsG: 38.0, fatG: 6.0, estimated: true },
      { name: 'Vegetable Kurma with Rice', calories: 265, proteinG: 6.0, carbsG: 48.0, fatG: 4.5, estimated: true },
      { name: 'Kothu Parotta (Veg)', calories: 290, proteinG: 6.0, carbsG: 44.0, fatG: 8.0, estimated: true },
      { name: 'Adai with Avial', calories: 220, proteinG: 7.0, carbsG: 38.0, fatG: 3.5, estimated: true },
    ],
    eggetarian: [
      { name: 'Egg Kothu Parotta', calories: 340, proteinG: 11.0, carbsG: 44.0, fatG: 11.0, estimated: true },
      { name: 'Egg Curry with Chapati', calories: 295, proteinG: 10.0, carbsG: 40.0, fatG: 8.0, estimated: true },
      { name: 'Egg Masala Dosa', calories: 285, proteinG: 9.5, carbsG: 38.0, fatG: 8.5, estimated: true },
      { name: 'Egg Rice Bowl', calories: 310, proteinG: 10.5, carbsG: 48.0, fatG: 7.0, estimated: true },
      { name: 'Omelette with Idiyappam', calories: 270, proteinG: 9.0, carbsG: 40.0, fatG: 6.5, estimated: true },
    ],
    'non-veg': [
      { name: 'Chicken Curry with Rice', calories: 365, proteinG: 18.0, carbsG: 48.0, fatG: 10.0, estimated: true },
      { name: 'Fish Fry with Rasam Rice', calories: 340, proteinG: 17.0, carbsG: 46.0, fatG: 9.0, estimated: true },
      { name: 'Mutton Biryani', calories: 410, proteinG: 19.0, carbsG: 50.0, fatG: 15.0, estimated: true },
      { name: 'Prawn Curry with Idiyappam', calories: 320, proteinG: 16.0, carbsG: 40.0, fatG: 9.0, estimated: true },
      { name: 'Chicken Kothu Parotta', calories: 385, proteinG: 17.0, carbsG: 44.0, fatG: 13.0, estimated: true },
      { name: 'Fish Kuzhambu with Rice', calories: 350, proteinG: 16.5, carbsG: 48.0, fatG: 8.5, estimated: true },
      { name: 'Chicken Pepper Fry with Parotta', calories: 375, proteinG: 17.5, carbsG: 42.0, fatG: 12.0, estimated: true },
      { name: 'Crab Curry with Rice', calories: 345, proteinG: 17.0, carbsG: 48.0, fatG: 8.0, estimated: true },
    ],
  },
};
