'use strict';

module.exports = [
  // ── LEGS ──────────────────────────────────────────────────────────────────
  {
    name: 'Bodyweight Squat',
    muscleGroup: 'legs',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: ['knee-pain'],
    substitutions: { 'knee-pain': 'Wall Sit' },
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10', intermediate: '12', advanced: '15' },
    note: 'Keep chest up, knees behind toes',
  },
  {
    name: 'Lunges',
    muscleGroup: 'legs',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: ['knee-pain'],
    substitutions: { 'knee-pain': 'Step Touch' },
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8 each leg', intermediate: '10 each leg', advanced: '12 each leg' },
    note: 'Step forward, lower back knee toward floor',
  },
  {
    name: 'Wall Sit',
    muscleGroup: 'legs',
    goals: ['weight-loss', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 3 },
    reps: { beginner: '20 sec', intermediate: '30 sec', advanced: '45 sec' },
    note: 'Back flat against wall, thighs parallel to floor',
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'legs',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['dumbbells'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10', intermediate: '12', advanced: '15' },
    note: 'Hold dumbbell at chest height, elbows inside knees',
  },
  {
    name: 'Barbell Squat',
    muscleGroup: 'legs',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['barbell'],
    contraindications: ['lower-back-pain'],
    substitutions: { 'lower-back-pain': 'Goblet Squat' },
    sets: { beginner: 3, intermediate: 4, advanced: 5 },
    reps: { beginner: '8', intermediate: '10', advanced: '12' },
    note: 'Bar on upper traps, brace core throughout',
  },

  // ── BACK ──────────────────────────────────────────────────────────────────
  {
    name: 'Superman Hold',
    muscleGroup: 'back',
    goals: ['weight-loss', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8', intermediate: '10', advanced: '12' },
    note: 'Lie face down, lift arms and legs simultaneously',
  },
  {
    name: 'Deadlift',
    muscleGroup: 'back',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['barbell'],
    contraindications: ['lower-back-pain'],
    substitutions: {},
    sets: { beginner: 3, intermediate: 4, advanced: 5 },
    reps: { beginner: '5', intermediate: '6', advanced: '8' },
    note: 'Neutral spine, hinge at hips, drive through heels',
  },
  {
    name: 'Dumbbell Row',
    muscleGroup: 'back',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: ['dumbbells'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10 each', intermediate: '12 each', advanced: '15 each' },
    note: 'Elbow drives back, squeeze shoulder blade at top',
  },
  {
    name: 'Pull-Up',
    muscleGroup: 'back',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['pull-up-bar'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '5', intermediate: '8', advanced: '12' },
    note: 'Dead hang start, chin clears bar',
  },

  // ── CHEST ─────────────────────────────────────────────────────────────────
  {
    name: 'Push-Up',
    muscleGroup: 'chest',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: ['shoulder-pain'],
    substitutions: { 'shoulder-pain': 'Incline Push-Up' },
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8', intermediate: '12', advanced: '20' },
    note: 'Body straight, elbows at 45°',
  },
  {
    name: 'Incline Push-Up',
    muscleGroup: 'chest',
    goals: ['weight-loss', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10', intermediate: '15', advanced: '20' },
    note: 'Hands on elevated surface reduces load on shoulders',
  },
  {
    name: 'Dumbbell Bench Press',
    muscleGroup: 'chest',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['dumbbells'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 3, intermediate: 4, advanced: 5 },
    reps: { beginner: '10', intermediate: '12', advanced: '15' },
    note: 'Lower to chest level, press straight up',
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────────────
  {
    name: 'Pike Push-Up',
    muscleGroup: 'shoulders',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8', intermediate: '10', advanced: '15' },
    note: 'Hips high, lower head toward floor',
  },
  {
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: ['dumbbells'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10', intermediate: '12', advanced: '15' },
    note: 'Press overhead, avoid arching lower back',
  },

  // ── ARMS ──────────────────────────────────────────────────────────────────
  {
    name: 'Tricep Dip',
    muscleGroup: 'arms',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8', intermediate: '12', advanced: '15' },
    note: 'Use chair or bench, elbows track back',
  },
  {
    name: 'Dumbbell Curl',
    muscleGroup: 'arms',
    goals: ['muscle-gain', 'general-fitness'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: ['dumbbells'],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '10', intermediate: '12', advanced: '15' },
    note: 'Curl to shoulder, lower with control',
  },

  // ── CORE ──────────────────────────────────────────────────────────────────
  {
    name: 'Plank',
    muscleGroup: 'core',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: ['lower-back-pain'],
    substitutions: { 'lower-back-pain': 'Dead Bug' },
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '20 sec', intermediate: '30 sec', advanced: '45 sec' },
    note: 'Neutral spine, brace abs, breathe steadily',
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'core',
    goals: ['weight-loss', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '6 each side', intermediate: '8 each side', advanced: '10 each side' },
    note: 'Lower back pressed to floor, extend opposite arm and leg',
  },
  {
    name: 'Crunch',
    muscleGroup: 'core',
    goals: ['weight-loss', 'muscle-gain', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '12', intermediate: '15', advanced: '20' },
    note: 'Curl shoulders off floor, chin off chest',
  },

  // ── FULL-BODY ─────────────────────────────────────────────────────────────
  {
    name: 'Burpee',
    muscleGroup: 'full-body',
    goals: ['weight-loss', 'general-fitness'],
    fitnessLevels: ['intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '8', intermediate: '10', advanced: '15' },
    note: 'Jump feet back to plank, push-up optional, explode up',
  },
  {
    name: 'Mountain Climber',
    muscleGroup: 'full-body',
    goals: ['weight-loss', 'general-fitness', 'maintenance'],
    fitnessLevels: ['beginner', 'intermediate', 'advanced'],
    equipment: [],
    contraindications: [],
    substitutions: {},
    sets: { beginner: 2, intermediate: 3, advanced: 4 },
    reps: { beginner: '20 sec', intermediate: '30 sec', advanced: '40 sec' },
    note: 'Hips level, drive knees to chest alternately',
  },
];
